Add LCD graphics
louisabricot/gbmu pull request #9
Opened 2023-01-29 16:46 UTC by 0x050f

2023-04-05 19:45 UTC, louisabricot commented on .github/workflows/ci.yml
Not sure that the gameboy font is very practical for the debugger, maybe look for a clearer font ?

2023-04-05 20:01 UTC, louisabricot requested changes
Replace the hardcoded values and let's merge !  It looks great !
Also, don't be shy with documentation 🧙‍♀️

2023-04-06 02:04 UTC, 0x050f commented on src/graphics/lcd.rs
> +            let c1: u8 = (((x * 255) / self.get_width()) % 255) as u8;
Will be replaced by GameBoy rendering

2023-04-06 02:05 UTC, 0x050f commented on .github/workflows/ci.yml
Actually the gameboy font isn't mandatory for dev -> Issued

2023-04-06 07:07 UTC, louisabricot approved these changes
PERFECT !!

2023-04-06 07:07 UTC, merged